before:
  hooks:
    - go mod download
builds:
  - main: main.go
    binary: helm-blob
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
      - plugin.yaml
      - scripts/install-plugin.sh
      - scripts/proxy.sh
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_{{ .Tag }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
