before:
  hooks:
    - go mod download
builds:
  - main: main.go
    binary: helm-blob
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
      - plugin.yaml
      - scripts/install-plugin.sh
      - scripts/proxy.sh
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_{{ .Tag }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers:
  - image_templates:
      # - docker.pkg.github.com/c123r/github-action-test/test:latest
      - registry.gitlab.com/c123r/goreleaser/helm-blob:v1

release:
  disable: true
