language: go
go:
  - "1.13"

env:
  - GO111MODULE=on

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libpcap-dev gcc

install:
  - go mod download

after_success:
  # Set up git user name and tag this commit
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(cat VERSION)}
  - git tag -a $TRAVIS_TAG $(git log --format=%h -1) -m "Generated tag from Travis CI based on VERSION file"
  - test -n "$TRAVIS_TAG" && curl -s https://raw.githubusercontent.com/goreleaser/get/master/latest | bash

deploy:
  - provider: script
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash

notifications:
  email: false
