name: "blob"
version: "0.4.0"
usage: "(Helm v3) Manage chart repositories on Blob Storage(Azure Blob, GCS, S3)"
description: |-
  (Helm v3) Manage chart repositories on Blob Storage(Azure Blob, GCS, S3).
command: "$HELM_PLUGIN_DIR/bin/helm-blob"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install-plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install-plugin.sh"
downloaders:
  - command: "/bin/proxy.sh"
    protocols:
      - "azblob"
      - "s3"
      - "gs"
