name: "blob"
version: "0.1.0"
usage: "Manage chart repositories on Blob Storage(Azure Blob, GCS, S3)"
description: |-
  The plugin provide support for azblob, s3, gs protocol to upload, delete charts and to work with repositories.
  https://github.com/C123R/helm-blob
command: "$HELM_PLUGIN_DIR/bin/helm-blob"
downloaders:
- command: "/bin/helm-blob.sh"
  protocols:
    - "azblob"
    - "s3"
    - "gs"